const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const API='/api'; let deferredPrompt=null, adminPin=sessionStorage.getItem('aakcPin')||'';
const events=[
['2026-09-11','18:00','Öffnung des Kerbeplatzes','Start in das Jubiläumswochenende'],['2026-09-11','19:00','Kerbe-Disco mit DJ Buzzin Lights','Happy Hour 18:30–19:30 Uhr'],['2026-09-11','20:00','Einlauf & Vereidigung','Kerbeborsch & Wuzzemädels'],['2026-09-11','21:30','Kerbeshow','Freitagabend im Festzelt'],
['2026-09-12','12:00','Kinderfest auf dem Kerbeplatz','mit Grillgut, Kaffee & Kuchen'],['2026-09-12','14:00','Schubkarrenrennen an den Gräben','Traditioneller Samstagnachmittag'],['2026-09-12','16:00','3. Altenhainer Bierpongturnier','Turnier auf dem Kerbeplatz'],['2026-09-12','18:00','Zelteinlass','Happy Hour 18:30–19:30 Uhr'],['2026-09-12','19:30','Jubiläumseinlauf aller Kerbeborsch seit 1976','Danach Party mit Partyfritteuse'],
['2026-09-13','11:00','Gottesdienst','Katholische Kirche Maria Geburt'],['2026-09-13','14:00','Festumzug durch Altenhain','Danach After-Umzugsparty'],['2026-09-13','17:00','Tombola','Kerbesonntag'],['2026-09-13','18:00','Beerdigung','Traditioneller Abschluss']
].map((e,i)=>({id:'e'+i,day:e[0],time:e[1],title:e[2],detail:e[3],start:new Date(`${e[0]}T${e[1]}:00+02:00`)}));
const dayNames={'2026-09-11':'Freitag, 11. September','2026-09-12':'Samstag, 12. September','2026-09-13':'Sonntag, 13. September'};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove('show'),3000)}
function switchView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.bottomnav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));location.hash=v==='start'?'':v;scrollTo(0,0);if(v==='fotos')loadGallery()}
$$('.bottomnav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));

document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));

if(location.hash) switchView(location.hash.slice(1));
function nextEvent(){return events.find(e=>e.start>Date.now())}
function tick(){const e=nextEvent();if(!e){$('#nextTitle').textContent='Die Wuzzekerb 2026 ist vorbei';$('#nextMeta').textContent='Nach de Kerb is vor de Kerb.';return}$('#nextTitle').textContent=e.title;$('#nextMeta').textContent=`${dayNames[e.day]} · ${e.time} Uhr · ${e.detail}`;let d=e.start-Date.now();const vals=[Math.floor(d/86400000),Math.floor(d%86400000/3600000),Math.floor(d%3600000/60000),Math.floor(d%60000/1000)];['#cdD','#cdH','#cdM','#cdS'].forEach((s,i)=>$(s).textContent=String(vals[i]).padStart(2,'0'));}
function renderToday(){const now=new Date();const iso=now.toLocaleDateString('en-CA',{timeZone:'Europe/Berlin'});let list=events.filter(e=>e.day===iso);if(!list.length){const n=nextEvent();list=n?events.filter(e=>e.day===n.day).slice(0,4):[];}$('#todayList').innerHTML=list.length?list.map(e=>`<div class="compactitem"><b>${e.time}</b><div><strong>${e.title}</strong><div class="muted">${e.detail}</div></div></div>`).join(''):'<p class="muted">Heute kein Programmpunkt.</p>'}
function renderSchedule(filter='all'){const now=Date.now(),next=nextEvent();const days=[...new Set(events.map(e=>e.day))].filter(d=>filter==='all'||filter===d);$('#schedule').innerHTML=days.map(d=>`<div class="day"><h3>${dayNames[d]}</h3>${events.filter(e=>e.day===d).map(e=>`<div class="event ${e.id===next?.id?'next':''} ${e.start<now?'past':''}"><div class="etime">${e.time}</div><div><b>${e.title}</b><br><small>${e.detail}</small></div><button onclick="downloadIcs('${e.id}')">📅</button></div>`).join('')}</div>`).join('')}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSchedule(b.dataset.day)});
function icsDate(d){return d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}
function makeIcs(items){return `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//AAKC//Wuzzekerb 2026//DE\r\n${items.map(e=>`BEGIN:VEVENT\r\nUID:${e.id}@wuzzekerb2026\r\nDTSTART:${icsDate(e.start)}\r\nSUMMARY:${e.title}\r\nDESCRIPTION:${e.detail}\r\nBEGIN:VALARM\r\nTRIGGER:-PT30M\r\nACTION:DISPLAY\r\nDESCRIPTION:In 30 Minuten: ${e.title}\r\nEND:VALARM\r\nEND:VEVENT`).join('\r\n')}\r\nEND:VCALENDAR`}
function dl(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/calendar'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.downloadIcs=id=>{const e=events.find(x=>x.id===id);dl(makeIcs([e]),`wuzzekerb-${id}.ics`)}; $('#allIcs').onclick=()=>dl(makeIcs(events),'wuzzekerb-2026-programm.ics'); $('#nextIcs').onclick=()=>{const e=nextEvent();if(e)downloadIcs(e.id)};
async function api(path,opt={}){const r=await fetch(API+path,opt);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`Fehler ${r.status}`);return r.json()}
async function loadNews(){try{const d=await api('/news');$('#newsList').innerHTML=d.items?.length?d.items.map(n=>`<div class="newsitem"><div>🔔</div><div><b>${n.title}</b><div>${n.body}</div><small class="muted">${new Date(n.createdAt).toLocaleString('de-DE')}</small></div></div>`).join(''):'<p class="muted">Noch keine Meldungen.</p>'}catch{}}
async function loadGallery(){try{const d=await api('/gallery');$('#gallery').innerHTML=d.items?.length?d.items.map(p=>`<div class="photo"><img loading="lazy" src="${p.url}" alt="Kerbefoto"><p>${p.caption||''}${p.name?`<br><b>📷 ${p.name}</b>`:''}</p></div>`).join(''):'<p class="muted">Noch keine freigegebenen Fotos.</p>'}catch{}}
$('#openUpload').onclick=()=>$('#uploadModal').classList.remove('hidden');$('#closeUpload').onclick=()=>$('#uploadModal').classList.add('hidden');
$('#uploadForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),file=fd.get('photo');if(file.size>5*1024*1024){$('#uploadStatus').textContent='Bitte maximal 5 MB.';return}$('#uploadStatus').textContent='Wird hochgeladen …';try{const r=await fetch(API+'/upload',{method:'POST',body:fd});if(!r.ok)throw new Error();e.target.reset();$('#uploadStatus').textContent='Danke! Das Foto wartet jetzt auf Freigabe.';toast('Foto eingereicht 📸')}catch{$('#uploadStatus').textContent='Upload fehlgeschlagen.'}}
async function enablePush(){if(!('serviceWorker'in navigator)||!('PushManager'in window)){toast('Push wird von diesem Browser nicht unterstützt.');return}const reg=await navigator.serviceWorker.ready;const key=await api('/push-public-key');if(!key.publicKey){toast('Push muss im Netlify-Admin noch eingerichtet werden.');return}const perm=await Notification.requestPermission();if(perm!=='granted')return;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(key.publicKey)});await api('/push-subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sub)});toast('Push-News aktiviert 🔔')}
function urlBase64ToUint8Array(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))} $('#pushBtn').onclick=enablePush;
$('#adminLoginBtn').onclick=async()=>{adminPin=$('#adminPin').value;try{await api('/admin-check',{headers:{'x-admin-pin':adminPin}});sessionStorage.setItem('aakcPin',adminPin);$('#adminLogin').classList.add('hidden');$('#adminArea').classList.remove('hidden');loadAdmin()}catch{toast('PIN falsch')}};
async function loadAdmin(){const p=await api('/gallery-admin',{headers:{'x-admin-pin':adminPin}});$('#pendingPhotos').innerHTML=p.items?.length?p.items.map(x=>`<div class="pending"><img src="${x.url}"><div><b>${x.name||'Anonym'}</b><p>${x.caption||''}</p><button class="pink" onclick="moderate('${x.id}','approve')">Freigeben</button> <button onclick="moderate('${x.id}','delete')">Löschen</button></div></div>`).join(''):'<p class="muted">Keine offenen Fotos.</p>'}
$('#sendNews').onclick=async()=>{await api('/push-send',{method:'POST',headers:{'content-type':'application/json','x-admin-pin':adminPin},body:JSON.stringify({title:$('#newsTitle').value,body:$('#newsBody').value})});toast('Push-News gesendet');$('#newsTitle').value='';$('#newsBody').value='';loadNews()};
window.moderate=async(id,action)=>{await api('/gallery-admin',{method:'POST',headers:{'content-type':'application/json','x-admin-pin':adminPin},body:JSON.stringify({id,action})});toast(action==='approve'?'Foto freigegeben':'Foto gelöscht');loadAdmin();loadGallery()};
if(adminPin){$('#adminLogin').classList.add('hidden');$('#adminArea').classList.remove('hidden');loadAdmin().catch(()=>{})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
renderToday();renderSchedule();tick();setInterval(tick,1000);loadNews();loadGallery();
